export const DataTechnologies = [
  { id: 1, name: "MONGO DB", tag: "mongo-db", description: ["tec.mongodb1", "tec.mongodb2"] },
  { id: 2, name: "EXPRESS JS", tag: "express", description: ["tec.express1", "tec.express2"] },
  { id: 3, name: "ANGULAR", tag: "angular", description: ["tec.angular1", "tec.angular2"] },
  { id: 4, name: "NODE JS", tag: "node", description: ["tec.node1", "tec.node2"] },
  { id: 5, name: "BOOTSTRAP", tag: "bootstrap", description: ["tec.bootstrap1", "tec.bootstrap2"] },
  { id: 6, name: "SPRING BOOT", tag: "spring-boot", description: ["tec.spring-boot1", "tec.spring-boot2"] },
  { id: 7, name: "REACT", tag: "react", description: ["tec.react1", "tec.react2"] },
  { id: 8, name: "SQL SERVER", tag: "sql-server", description: ["tec.sql-server1", "tec.sql-server2"] },
  { id: 9, name: "AWS LAMBDA", tag: "aws-lambda", description: ["tec.aws-lambda1", "tec.aws-lambda2"] },
  { id: 10, name: "AWS S3", tag: "aws-s3", description: ["tec.aws-s31", "tec.aws-s32"] },
  { id: 11, name: "AWS RDS", tag: "aws-rds", description: ["tec.aws-rds1", "tec.aws-rds2"] },
  { id: 12, name: "AWS EC2", tag: "aws-ec2", description: ["tec.aws-ec21", "tec.aws-ec22"] },
  { id: 13, name: "LARAVEL", tag: "laravel", description: ["tec.laravel1", "tec.laravel2"] },
  { id: 14, name: "C#", tag: "c-sharp", description: ["tec.c-sharp1", "tec.c-sharp2"] },
  { id: 15, name: "DOCKER", tag: "docker", description: ["tec.docker1", "tec.docker2"] },
  { id: 16, name: "GIT", tag: "git", description: ["tec.git1", "tec.git2"] },
  { id: 17, name: "MOCKITO", tag: "mockito", description: ["tec.mockito1", "tec.mockito2"] },
  { id: 18, name: "JEST JS", tag: "jest", description: ["tec.jest1", "tec.jest2"] },
  { id: 19, name: "SPRING", tag: "spring", description: ["tec.spring1", "tec.spring2"] },
  { id: 20, name: "POSTMAN", tag: "postman", description: ["tec.postman1", "tec.postman2"] },
  { id: 47, name: "FIGMA", tag: "figma", description: ["tec.figma1", "tec.figma2"] },
  { id: 48, name: "NEST JS", tag: "nestjs", description: ["tec.nestjs1", "tec.nestjs2"] },
  { id: 39, name: "SASS", tag: "sass", description: ["tec.sass1", "tec.sass2"] },
  { id: 40, name: ".NET CORE", tag: "core", description: ["tec.core1", "tec.core2"] },
  { id: 28, name: "VISUAL BASIC SCRIPT", tag: "vbscript", description: ["tec.vbscript1", "tec.vbscript2"] },
  { id: 27, name: "ASP.NET", tag: "asp", description: ["tec.asp1", "tec.asp2"] },
  { id: 21, name: "MYSQL", tag: "mysql", description: ["tec.mysql1", "tec.mysql2"] },
  { id: 22, name: "LIT HTML", tag: "lit-html", description: ["tec.lit-html1", "tec.lit-html2"] },
  { id: 23, name: "WORDPRESS", tag: "wordpress", description: ["tec.wordpress1", "tec.wordpress2"] },
  { id: 26, name: "PHP", tag: "php", description: ["tec.php1", "tec.php2"] },
  { id: 41, name: "TRELLO", tag: "trello", description: ["tec.trello1", "tec.trello2"] },
  { id: 42, name: "JIRA", tag: "jira", description: ["tec.jira1", "tec.jira2"] },
  { id: 43, name: "KANBAN", tag: "kanban", description: ["tec.kanban1", "tec.kanban2"] },
  { id: 45, name: "SCRUM", tag: "scrum", description: ["tec.scrum1", "tec.scrum2"] },
  { id: 46, name: "CSS", tag: "css", description: ["tec.css1", "tec.css2"] },
  { id: 44, name: "HTML", tag: "html", description: ["tec.html1", "tec.html2"] },
  { id: 24, name: "JQUERY", tag: "jquery", description: ["tec.jquery1", "tec.jquery2"] },
  { id: 29, name: "SQL", tag: "sql", description: ["tec.sql1", "tec.sql2"] },
  { id: 25, name: "ANDROID STUDIO", tag: "android-studio", description: ["tec.android-studio1", "tec.android-studio2"] },
  { id: 30, name: "JAVA", tag: "java", description: ["tec.java1", "tec.java2"] },
  { id: 37, name: "API REST", tag: "rest", description: ["tec.rest1", "tec.rest2"] },
  { id: 38, name: "API SOAP", tag: "soap", description: ["tec.soap1", "tec.soap2"] },
  { id: 33, name: "VISUAL STUDIO CODE", tag: "visual-studio-code", description: ["tec.visual-studio-code1", "tec.visual-studio-code2"] },
  { id: 34, name: "VISUAL STUDIO", tag: "visual-studio", description: ["tec.visual-studio1", "tec.visual-studio2"] },
  { id: 35, name: "JAVASCRIPT", tag: "javascript", description: ["tec.javascript1", "tec.javascript2"] },
  { id: 36, name: "TYPESCRIPT", tag: "typescript", description: ["tec.typescript1", "tec.typescript2"] },
  { id: 31, name: "ADOBE ILLUSTRATOR", tag: "illustrator", description: ["tec.illustrator1", "tec.illustrator2"] },
  { id: 32, name: "ADOBE PHOTOSHOP", tag: "photoshop", description: ["tec.photoshop1", "tec.photoshop2"] },
]

